name: Unity CI/CD

on:
  push:
    branches: [ "develop", "main" ]

jobs:
  build-and-email:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Build Unity Project
      - name: Build project
        uses: game-ci/unity-builder@v2
        with:
          unityVersion: 6000.0.55f1
          targetPlatform: StandaloneWindows64
        env:
          UNITY_EMAIL: ${{ secrets.MM }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

      # Zip the build
      - name: Zip Build
        run: |
          mkdir output
          zip -r output/Game-Build.zip build/

      # Upload build artifact
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Game-Build
          path: output/Game-Build.zip

      # Send Email Notification with Build Attachment
      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MOEKETSIMOTSAGE }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "CI Build - ${{ github.repository }}"
          to: "team@example.com"
          from: "CI Bot <ci@example.com>"
          body: |
            A new push triggered a Unity build.

            Repo: ${{ github.repository }}
            Branch: ${{ github.ref_name }}
            Commit: ${{ github.sha }}

            Build is ready for testing.
          attachments: output/Game-Build.zip
