name: CI/CD - Email Only

on:
  push:
    branches: [ "develop", "main" ]

jobs:
  email-only:
    runs-on: windows-latest
    steps:
      # 1️⃣ Checkout repo
      - uses: actions/checkout@v3

      # 2️⃣ Zip pre-existing build folder (adjust path as needed)
      - name: Zip Build
        shell: pwsh
        run: |
          mkdir output
          Compress-Archive -Path prebuilt_build_folder/* -DestinationPath output/Game-Build.zip

      # 3️⃣ Upload artifact
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Game-Build
          path: output/Game-Build.zip

      # 4️⃣ Send email notification
      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "CI/CD Notification - ${{ github.repository }}"
          to: "team@example.com"
          from: "CI Bot <ci@example.com>"
          body: |
            A new push triggered a CI/CD workflow.

            Repo: ${{ github.repository }}
            Branch: ${{ github.ref_name }}
            Commit: ${{ github.sha }}

            The prebuilt files are ready for testing.
          attachments: output/Game-Build.zip
