name: Unity CI/CD - Windows Personal

on:
  push:
    branches: [ "develop", "main" ]

jobs:
  build-and-email:
    runs-on: windows-latest   # Windows runner required for StandaloneWindows64
    steps:
      - uses: actions/checkout@v3

      # Build Windows without license
      - name: Build Windows
        uses: game-ci/unity-builder@v2
        with:
          unityVersion: 6000.0.55f1
          targetPlatform: StandaloneWindows64
          buildName: GameBuild
          buildPath: build/Windows
          activateLicense: false

      # Zip the build using PowerShell
      - name: Zip Build
        shell: pwsh
        run: |
          mkdir output
          Compress-Archive -Path build/Windows/* -DestinationPath output/Game-Build-Windows.zip

      # Upload artifact
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Game-Build
          path: output/Game-Build-Windows.zip

      # Send email
      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "CI Build - ${{ github.repository }}"
          to: "team@example.com"
          from: "CI Bot <ci@example.com>"
          body: |
            A new push triggered a Unity build.

            Repo: ${{ github.repository }}
            Branch: ${{ github.ref_name }}
            Commit: ${{ github.sha }}

            Windows build is ready for testing.
          attachments: output/Game-Build-Windows.zip
